# Generated by Django 5.0.4 on 2024-05-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_purchase_order_acknowledgment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='delivery_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='issue_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='purchase_order',
            name='order_date',
            field=models.DateTimeField(),
        ),
    ]
