# Generated by Django 5.0.4 on 2024-05-05 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_purchase_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='issue_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
